pdfcrop svmIntro.pdf svmIntro.pdf
pdfcrop allAggPerf.pdf allAggPerf.pdf
pdfcrop polCat_cat1_All_sep.pdf polCat_cat1_All_sep.pdf 
pdfcrop polCat_cat2_All_sep.pdf polCat_cat2_All_sep.pdf 
pdfcrop polCat_cat3_All_sep.pdf polCat_cat3_All_sep.pdf 
pdfcrop polCat_cat4_All_sep.pdf polCat_cat4_All_sep.pdf 
pdfcrop military_All_sep.pdf military_All_sep.pdf
pdfcrop monarchy_All_sep.pdf monarchy_All_sep.pdf
pdfcrop party_All_sep.pdf party_All_sep.pdf
pdfcrop polCat_perfChange.pdf polCat_perfChange.pdf
pdfcrop military_perfChange.pdf military_perfChange.pdf
pdfcrop polCat_wrdCloud.pdf polCat_wrdCloud.pdf
pdfcrop bin_wrdCloud.pdf bin_wrdCloud.pdf
pdfcrop polCat_cat1_2012_map.pdf polCat_cat1_2012_map.pdf
pdfcrop polCat_cat2_2012_map.pdf polCat_cat2_2012_map.pdf
pdfcrop polCat_cat3_2012_map.pdf polCat_cat3_2012_map.pdf
pdfcrop polCat_cat4_2012_map.pdf polCat_cat4_2012_map.pdf
pdfcrop military_2010_map.pdf military_2010_map.pdf
pdfcrop monarchy_2010_map.pdf monarchy_2010_map.pdf
pdfcrop party_2010_map.pdf party_2010_map.pdf
